name: bsiPytorch
channels:
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - accelerate=1.10.1
  - aom=3.6.0
  - appnope=0.1.4
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - dataclasses=0.8
  - datasets=4.0.0
  - dav1d=1.2.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - deprecated=1.2.13
  - dill=0.3.8
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.5.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.7.7
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.15.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopenblas=0.3.29
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - librsvg=2.56.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libtheora=1.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=3.0
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.2
  - opentelemetry-api=1.30.0
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.2
  - pango=1.50.7
  - parso=0.8.5
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - protobuf=5.29.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.21
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - re2=2024.07.02
  - readline=8.3
  - regex=2024.11.6
  - requests=2.32.5
  - safetensors=0.5.3
  - setuptools=72.1.0
  - six=1.17.0
  - sleef=3.5.1
  - snappy=1.2.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.13.3
  - tesseract=5.2.0
  - tk=8.6.15
  - tokenizers=0.21.0
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - wrapt=1.17.0
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - bsi-ops==0.0.0
